### ISSUE TITLE
compass not detected got -1

### ISSUE THREAD

**Issue by Twometer** [ericalbers/ICM20948_DMP_Arduino#7]
Hi,

first of all, thanks for this port and working through the Invensense code!

But, I am trying to use 9-axis DOF and i keep getting this error: 

`compass not detected got -1`

I tried all compass IDs and all addresses, and I can't get the compass to be detected. 6-axis fusion works.

Do you know what the cause can be?

Thanks!

**Comment by Twometer** [comment]
I pulled AD0 high and hard-coded 0x69 as the address, and now it works.

If i try to read the magnetometer manually the values are constant, but the DMP gives me drift-corrected (I think) 9-axis vectors so I think it's solved.

**Comment by spiritplumber** [comment]
thank you for giving me something to try!
