### ISSUE TITLE
Quaternion Output too slow

### ISSUE THREAD

**Issue by AsternA** [ericalbers/ICM20948_DMP_Arduino#9]
Hey Guys, 

I have successfully compiled and the code works great on the Ardunio. Great Work!!

I am only interested in Quaternion Output so i have commented out all other serial.println's. Is there anyway to increase the output rate because right now it only outputs 1 every 2-3 seconds which is very slow.

Any help is appreciated! Thanks!!

**Comment by Glavin001** [comment]
@AsternA : Did you find a solution? I am experiencing the same problem.

**Comment by AsternA** [comment]
I did and i forgot to close this issue

this issue is a duplicate of  "Increase update rate for streaming rotation vector (9-axis DMP) #1 " in the closed issues.

In addition, with the help of https://x-io.co.uk/open-source-ahrs-with-x-imu/ I am able to output Quaternions without the DMP with the default ICM20948 header file.

The Quaternion output of both the DMP and the AHRS were tested side by side using PyTeapot-Quaternion-Euler-cube-rotation
found on Github and were found to be equivalent :)
